[project]
name = "weekly_update"
version = "0.1.0"
description = "marketing agency using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools, agentops]>=0.51.1,<0.52",
    "google-api-python-client>=2.139.0",
    "gspread>=6.1.2,<7",
    "pyairtable>=2.3.3,<3",
    "llama-index>=0.10.65,<0.11",
    "llama-index-llms-openai>=0.1.29,<0.2",
    "jsonpath-ng>=1.6.1,<2",
    "langchain-anthropic>=0.1.20,<0.2",
    "ollama>=0.2.1,<0.3",
    "pydantic>=2.8.2,<3",
    "langchain-groq>=0.1.9,<0.2",
    "langchain-experimental>=0.0.64,<0.0.65",
]

[project.scripts]
weekly_update = "weekly_update.main:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
