extract_data_task:
  description: >
    Extract data that is required for the query {query}.
  expected_output: >
    Database result for the query.

analyze_data_task:
  description: >
    Analyze the data from the database and write an analysis for {query}.
  expected_output: >
    Detailed analysis text.

write_report_task:
  description: >
    Write an executive summary of the report from the analysis. The report
    must be less than 100 words.
  expected_output: >
    Markdown report.
